baseURL = "https://cucumber.io/"
languageCode = "en-us"
title = "Cucumber Documentation"
theme = "cucumber-sb"
enableInlineShortcodes = true


[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

pygmentsUseClassic = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[markup.goldmark.renderer]
  unsafe = true
